name: Debug Build
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Check files
      run: |
        echo "Files in repository:"
        ls -la
        echo "Checking main.js exists:"
        ls -la main.js || echo "main.js not found"
        echo "Checking package.json:"
        cat package.json
    
    - name: Install dependencies
      run: npm install
    
    - name: List installed packages
      run: npm list --depth=0
    
    - name: Try build
      run: npm run build-mac
